services:
  norn:
    image: josiahdc/norn:0.1
    build:
      context: .
    env_file: "./norn.env"
    environment:
      HF_HOME: /atelier/cache
    volumes:
      - cache:/atelier/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  cache:
    external: false
