services:
  norn:
    image: josiahdc/norn
    build: .
    ports:
      - "23077:23000"
    env_file: "./norn.env"
    environment:
      HF_HOME: /atelier/hf_home
    volumes:
      - /etc/hf_home:/atelier/hf_home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
